[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Monad Mainnet Configuration
eth_rpc_url = "https://rpc.monad.xyz"
chain_id = 143

[rpc_endpoints]
monad = "${MONAD_RPC_URL}"
monad_mainnet = "https://rpc.monad.xyz"

[etherscan]
monad = { key = "${MONAD_ETHERSCAN_API_KEY}", url = "https://api.monadscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
